# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies on macOS
        if: matrix.config.os == 'macos-latest'
        run: |
          echo "Updating Homebrew..."
          brew update || echo "Homebrew update failed; continuing..."
          echo "Installing Ghostscript and qpdf..."
          brew install gs qpdf || echo "Failed to install Ghostscript or qpdf"

      - name: Verify system dependencies on macOS
        if: matrix.config.os == 'macos-latest'
        run: |
          echo "Checking installed utilities..."
          which gs || echo "Ghostscript not found"
          which qpdf || echo "qpdf not found"

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          use-cloud: true

      - name: Install R dependencies
        run: |
          echo "Installing required R packages..."
          Rscript -e 'install.packages(c("data.table", "ggplot2", "nnet", "doParallel", "parallel", "foreach", "stringr", "tidyverse", "dplyr", "rlang", "reshape2", "speedglm", "methods", "Hmisc", "splines"), repos = "https://cran.rstudio.com")'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'

